version: 2
updates:
  # Maintain dependencies for the Java Maven backend
  - package-ecosystem: "maven"
    directory: "/backend" # Look for pom.xml here
    schedule:
      interval: "monthly"

  # Maintain dependencies for the Node.js frontend
  - package-ecosystem: "npm"
    directory: "/frontend" # Look for package.json here
    schedule:
      interval: "monthly"

 # @author -  Ram-Ambati
